### ISSUE TITLE
Allow configuration of base config location

### ISSUE THREAD

**Issue by lewiscowper** [pokanop/nostromo#26]
It'd be really great if we could customise the location (with an env variable or similar) of `~/.nostromo`. I personally (even on macOS) use the XDG directory spec env variables, so being able to store configs in `XDG_CONFIG_HOME` (for me that's `~/.config`, would be really great. Especially when #21 lands, it'd be good to potentially consider having a different location for in-use config file(s), and the shell file backups. (Potentially `XDG_CACHE_HOME` as that's the one for (non-essential) cached files).

For the reading from a custom config location alone, I'd be happy to take a look at solving it, if it's something you'd like to see the project support. Happy to take suggestions on naming a custom env variable too. (`NOSTROMO_CONFIG` for example).

**Comment by saheljalal** [comment]
Yeah, that'd be awesome if you wanted to help out on it.

In the absence of the env var, assuming we would still default to `~/.nostromo`. And how about `NOSTROMO_HOME` for the name? Let's update the README as well.

**Comment by lewiscowper** [comment]
Yeah, I'd keep the defaults the same as it's a reasonable default, I just like keeping my `~` clear of as many dot files as possible :)

I'll post a PR in the next few hours I guess
