### ISSUE TITLE
still having issues with nostromo

### ISSUE THREAD

**Issue by sinanlag** [pokanop/nostromo#35]
I have defined this command in nostromo:
+--------------+-------------------------------------+
| keypath     | mpnr                                    |
| alias          | mpnr                                    |
| command  | mpv --no-resume-playback |
| code          | false                                    | 
| mode         | concatenate                        | 
| aliasOnly   | false                                    |
+--------------+-------------------------------------+
Copied these link addresses from youtube.com
1) 'https://www.youtube.com/watch?v=LjhCEhWiKXk' 
2) 'https://www.youtube.com/watch?v=adLGHcj_fmA'

executed the following:
mpv  --no-resume-playback "link address 1) above" ; ## success 
mpv  --no-resume-playback "link address 2) above" ; ## success

executed these:
mpnr "link address 1) above" ; failed
mpnr "link address 2) above" ; failed

Error messages are same for both, as follows:
   - no matches found: 'the youtube link address specified'

What am I doing wrong?

Another issue (perhaps):

I have never been able to get nostromo to process a path/filename with space characters. Unless I edit the yaml? Which I haven't done.

**Comment by saheljalal** [comment]
I was able to make the command execute correctly by using quotes around the link. For some reason it seems to be trying to glob something and failing otherwise. This works like this:
```sh
mpnr "https://www.youtube.com/watch\?v\=LjhCEhWiKXk"
```

Other arguments seem ok, but the link requires quotes.
